daemon: false
log:
    displayLevel: 1
    fileLevel: 1
    filePath: .
    activityFilePath: .
    fileRoot: DVM-DVRS1
network:
    enable: true
    id: xNODE-IDx
    address: 10.147.17.245
    port: 63030
    jitter: 360
    password: "Centrunk!"
    slot1: true
    slot2: true
    updateLookups: false
    allowActivityTransfer: true
    allowDiagnosticTransfer: true
    debug: false
    restEnable: true
    restAddress: xZT-IPx
    restPort: 9991
    restPassword: "Centrunk!"
    restDebug: false
protocols:
    dmr:
        enable: false
        beacons:
            enable: false
            interval: 60
            duration: 3
        control: 
            dedicated: false
            enable: false
            slot: 1
        embeddedLCOnly: false
        dumpTAData: true
        dumpDataPacket: false
        repeatDataPacket: true
        dumpCsbkData: false
        verifyReg: false
        nRandWait: 8
        backOff: 1
        callHang: 5
        txHang: 8
        silenceThreshold: 21
        queueSize: 31
        verbose: true
        debug: false
    p25:
        enable: true
        tduPreambleCount: 6
        control:
            enable: true
            ackRequests: true
            dedicated: false
            broadcast: false
            interval: 300
            duration: 1
            disableTSDUMBF: false
            enableTimeDateAnn: true
        voiceOnControl: false
        disableCompositeFlag: false
        inhibitIllegal: false
        legacyGroupGrnt: true
        legacyGroupReg: false
        verifyAff: false
        verifyReg: false
        dumpDataPacket: false
        repeatDataPacket: true
        dumpTsbkData: false
        callHang: 5
        noStatusAck: false
        noMessageAck: true
        unitToUnitAvailCheck: true
        localEmergAlarm: true
        sndcpGrant: false
        silenceThreshold: 124
        disableNetworkHDU: false
        emergDisabled: false
        queueSize: 15
        verbose: true
        debug: false
    nxdn:
        enable: false
        control:
            enable: false
            dedicated: false
            broadcast: true
            interval: 300
            duration: 1
        voiceOnControl: false
        disableCompositeFlag: false
        verifyAff: false
        verifyReg: false
        dumpRcchData: false
        callHang: 5
        silenceThreshold: 14
        queueSize: 12
        verbose: true
        debug: false
system:
    identity: xIDENTITYx
    timeout: 180
    duplex: true
    simplexSameFrequency: false
    modeHang: 1
#    rfModeHang: 10
#    netModeHang: 10
    fixedMode: true
    rfTalkgroupHang: 10
    activeTickDelay: 5
    idleTickDelay: 5
    localTimeOffset: -6
    #Replace with your Local Time offset from UTC
    info:
        latitude: 30.299419 
        longitude: -97.691909
        height: 30
        power: 1
        location: "Texas, USA"
    config:
        authoritative: true
        channelId: 3
        channelNo: 910
        dmrNetId: 1
        controlCh:
            restAddress: xCC-ZT-IPx
            restPort: 9991
            restPassword: "Centrunk!"
        voiceChNo:
            - channelNo: 910
#ChannelNo here must match channelNo above OR the ChannelNo in the other voice Channels
              restAddress: xZT-IPx
#Can be set to Zero Tier IP if only using one computer. Ports need to be different from VC and CC if on same board
              restPort: 9991
              restPassword: "Centrunk!"
#Must Match the RCON password you set in this OR the Voice Channels Config
        colorCode: 1
        nac: xNACx
#Replace X with the last digit of your site ID
        ran: 1
        pSuperGroup: 0911
        netId: DEE00
        sysId: 13B
        rfssId: 1
        siteId: xSITEx
    modem:
        protocol:
            type: "uart" # Valid values are "null", and "uart"
            uart:
                port: /dev/ttyAMA0
                speed: 115200
        rxInvert: false
        txInvert: false
        pttInvert: false
        dcBlocker: true
        cosLockout: false
        fdmaPreamble: 80
        dmrRxDelay: 7
        p25CorrCount: 8
        dmrFifoLength: 505
        p25FifoLength: 442
        nxdnFifoLength: 538
        hotspot:
            dmrDiscBWAdj: 0 # Valid values between -128 and 128
            dmrPostBWAdj: 0 # Valid values between -128 and 128
            p25DiscBWAdj: 0 # Valid values between -128 and 128
            p25PostBWAdj: 0 # Valid values between -128 and 128
            nxdnDiscBWAdj: 0 # Valid values between -128 and 128
            nxdnPostBWAdj: 0 # Valid values between -128 and 128
            adfGainMode: 0 # 0 - Auto, 1 - Auto High Lin, 2 - Low, 3 - High
            afcEnable: false
            afcKI: 11
            afcKP: 4
            afcRange: 1
            txTuning: 0 # Freq offset for the hotspot, in hz
            rxTuning: 0
        repeater:
            dmrSymLvl3Adj: 0 # Valid values between -128 and 128
            dmrSymLvl1Adj: 0 # Valid values between -128 and 128
            p25SymLvl3Adj: 0 # Valid values between -128 and 128
            p25SymLvl1Adj: 0 # Valid values between -128 and 128
            nxdnSymLvl3Adj: 0 # Valid values between -128 and 128
            nxdnSymLvl1Adj: 0 # Valid values between -128 and 128
        softpot:
            rxCoarse: 127
            rxFine: 127
            txCoarse: 127
            txFine: 127
            rssiCoarse: 127
            rssiFine: 127
        rxDCOffset: 0 # Valid values between -128 and 128
        txDCOffset: 0 # Valid values between -128 and 128
        rxLevel: 50
        txLevel: 50
#        cwIdTxLevel: 50
#        dmrTxLevel: 50
#        p25TxLevel: 50
#        nxdnTxLevel: 50
        rssiMappingFile: RSSI.dat
        packetPlayoutTime: 10
        disableOFlowReset: false
        ignoreModemConfigArea: false
        dumpModemStatus: false
        trace: false
        debug: false
    cwId:
        enable: true
        time: 15
        callsign: WRUP970
    iden_table:
        file: /opt/centrunk/dvmhost/iden_table.dat
        time: 30
    radio_id:
        file: /opt/centrunk/dvmhost/rid_acl.dat
        time: 2
        acl: true
    talkgroup_id:
        file: /opt/centrunk/dvmhost/tg_acl.dat
        time: 2
        acl: true
